api/urls.py
from django.urls import path
from .views_api import tearsheet_api

# /api/v1/
app_name = "api"

urlpatterns = [
    path(
        "<str:tearsheet_slug>/", view=tearsheet_api
        )
]

bddw_prices/users/urls.py
from django.urls import path

from bddw_prices.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

csv_imports/urls.py
from django.urls import path

from .views import (
    export_all_formula_price_records,
    export_all_price_records,
    export_all_pricelist_records,
    export_sorting_records,
    formula_records_template,
    price_records_template,
    sorting_upload,
    upload,
    upload_formula_price_records,
)

app_name = "csv_imports"

urlpatterns = [
    path("", view=upload, name="upload"),
    path(
        "export-price-records",
        view=export_all_price_records,
        name="export_price_records",
    ),
    path(
        "export-pricelist-records",
        view=export_all_pricelist_records,
        name="export_pricelist_records",
    ),
    path("upload-formula/", view=upload_formula_price_records, name="upload_formula"),
    path(
        "export-form-records",
        view=export_all_formula_price_records,
        name="export_formula",
    ),
    path(
        "price-records-template/", view=price_records_template, name="normal_template"
    ),
    path("form-records-template/", view=formula_records_template, name="form_template"),
    path("sorting-upload/", view=sorting_upload, name="sorting_upload"),
    path("sorting-export/", view=export_sorting_records, name="sorting_export"),
]

bddw_prices/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for bddw prices.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

bddw_prices/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

bddw_prices/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

bddw_prices/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("home")


user_redirect_view = UserRedirectView.as_view()

bddw_prices/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from formula_tear_sheets.models import FormulaTearSheet
from price_records.models import (
    FormulaPriceListPriceRecord,
    FormulaPriceRecord,
    PriceListPriceRecord,
    PriceRecord,
)
from products.models import CatSeriesItem
from tear_sheets.models import TearSheet


@login_required
def snapshot(request):
    return render(
        request,
        "snapshot.html",
        {
            "cat_series_items": CatSeriesItem.objects.all(),
            "cat_series_items_with_formula": [
                x for x in CatSeriesItem.objects.all() if x.has_formula()
            ],
            "tear_sheets": TearSheet.objects.all(),
            "tear_sheets__last_updated": TearSheet.objects.all()
            .order_by("updated_on")
            .last(),
            "price_records": PriceRecord.objects.all(),
            "formula_tear_sheets": FormulaTearSheet.objects.all(),
            "formula_tear_sheets__last_updated": FormulaTearSheet.objects.all()
            .order_by("updated_on")
            .last(),
            "formula_tear_sheets__price_records": FormulaPriceRecord.objects.all(),
            "pricelist_records": PriceListPriceRecord.objects.all(),
            "pricelist_records__last_updated": PriceListPriceRecord.objects.all()
            .order_by("updated_on")
            .last(),
            "formula_price_list__price_records": FormulaPriceListPriceRecord.objects.all(),
            "formula_price_list__last_updated": FormulaPriceListPriceRecord.objects.all()
            .order_by("updated_on")
            .last(),
        },
    )

bddw_prices/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}bddw sales tools{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Behold My Awesome Project!">
    <meta name="author" content="lance">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      <!-- Bootstrap JS -->
      <script defer src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->
      <script src="https://unpkg.com/htmx.org@1.7.0"></script>
      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

  </head>

  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
  style="text-transform: uppercase; font-family: 'Source Sans Pro', sans-serif; letter-spacing: 0.05em; font-size: 12px; color: #8B8A86">
  <div style="padding-top: 15; padding-bottom: 15; background-color: #f8f9fa!important;">
	  <ul style="font-size: 16px;">

          {% if request.user.is_authenticated %}
      <li style="color: black;  padding-left: 48px; padding-right: 30px; display: inline;"><a href="{% url 'react_views:r_search:search' %}">BDDW SALES TOOLS</li>
		  <li style="padding-right: 30px; display: inline;"><a style="color: grey "href="{% url 'react_views:r_search:search' %}">TEARSHEETS</a></li>
      {% comment %}
		  <li style="padding-right: 30px; display: inline;"><a style="color: grey" href="{% url 'tearsheets:list' %}">TEARSHEETS</a></li>
		  <li style="padding-right: 30px; display: inline;"><a style="color: grey" href="{% url 'formula_tearsheets:list' %}">FORMSHEETS</a></li>
		  <li style="padding-right: 30px; display: inline;"><a style="color: grey"  href="{% url 'gbp:list' %}">GBP TEARSHEETS</a></li>
		  <li style="padding-right: 30px; display: inline;"><a style="color: grey"  href="{% url 'form_gbp:list' %}">GBP FORMSHEETS</a></li>
      {% endcomment %}
		  <li style="padding-right: 30px; display: inline;"><a style="color: grey" href="{% url 'react_views:r_price_lists:list' %}">PRICELISTS</a></li>
		  <li style="padding-right: 30px; display: inline;"><a style="color: grey" href="{% url 'csv_imports:upload' %}">CSV</a></li>
		  <li style="padding-right: 30px; display: inline;"><a style="color: grey" href="{% url 'admin:index' %}">ADMIN</a></li>
		  <li style="padding-right: 30px; display: inline;"><a style="color: grey" href="{% url 'account_logout' %}">LOGOUT</a></li>
         {% else %}
		  <li style="font-size: 23px; color: black;  padding-left: 15px; padding-right: 30px; display: inline;">BDDW SALES TOOLS</li>
		  <li style="padding-right: 30px; display: inline;"><a style="color: grey" href="{% url 'account_login' %}">LOGIN</a></li>
         {% endif %}
	  <ul>
  </div>

    <div class="pt-2 container">

      {% block content %}

      {% endblock content %}

    </div>

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })    </script>
    {% endblock inline_javascript %}

    <div class="footer" style="height: 100px;">
    </div>

  </body>
</html>

bddw_prices/templates/react_base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}bddw sales tools{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Behold My Awesome Project!">
    <meta name="author" content="lance">
    {% block css %}
    <!-- This file stores project-specific CSS -->
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <!-- Your stuff: Third-party javascript libraries go here -->
      <!-- place project specific Javascript in this file -->

    {% endblock javascript %}

  </head>

  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
  style="text-transform: uppercase; font-family: 'Source Sans Pro', sans-serif; letter-spacing: 0.05em; font-size: 12px; color: #8B8A86">
  <div style="padding-top: 15; padding-bottom: 15; background-color: #f8f9fa!important;">
	  <ul style="font-size: 16px;">
      <li style="color: black;  padding-left: 48px; padding-right: 30px; display: inline;"><a href="{% url 'react_views:r_search:search' %}">BDDW SALES TOOLS</li>
		  <li style="padding-right: 30px; display: inline;"><a href="{% url 'react_views:r_search:search' %}">Tearsheets</a></li>
      {% comment %}
		  <li style="padding-right: 30px; display: inline;"><a href="{% url 'tearsheets:list' %}">TEARSHEETS</a></li>
		  <li style="padding-right: 30px; display: inline;"><a href="{% url 'formula_tearsheets:list' %}">FORMSHEETS</a></li>
		  <li style="padding-right: 30px; display: inline;"><a href="{% url 'gbp:list' %}">GBP TEARSHEETS</a></li>
		  <li style="padding-right: 30px; display: inline;"><a href="{% url 'form_gbp:list' %}">GBP FORMSHEETS</a></li>
      {% endcomment %}
		  <li style="padding-right: 30px; display: inline;"><a href="{% url 'react_views:r_price_lists:list' %}">PRICELISTS</a></li>
		  <li style="padding-right: 30px; display: inline;"><a href="{% url 'csv_imports:upload' %}">CSV</a></li>
		  <li style="padding-right: 30px; display: inline;"><a href="{% url 'admin:index' %}">ADMIN</a></li>
		  <li style="padding-right: 30px; display: inline;"><a href="{% url 'account_logout' %}">LOGOUT</a></li>
	  <ul>
  </div>

  <div class="pt-5 container">
    <div style="height: 30px"></div>
    {% comment %} {% if messages %}
      {% for message in messages %}
        <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %} {% endcomment %}
    {% block content %}

    {% endblock content %}

  </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })    </script>
    {% endblock inline_javascript %}

    <div class="footer" style="height: 100px;">
    </div>

  </body>
</html>

bddw_prices/templates/snapshot.html
{% extends 'base.html' %}

{% block content %}

<h2 class="pt-5">tearsheets snapshot</h2>
<table class="table table-striped">
  <caption>bddwsalestools.com data</caption>
  <thead>
    <th>data type</th>
    <th>number</th>
    <th>last updated</th>
  </thead>
  <tr>
    <td>category series items</td>
    <td>{{cat_series_items | length}}</td>
    <td></td>
  </tr>
  <tr>
    <td>category series items w/ price formulas</td>
    <td>{{cat_series_items_with_formula | length}}</td>
    <td></td>
  </tr>
  {% comment %} <tr>
    <td class="text-center"><strong>NORMAL TEAR SHEETS</strong></td>
    <td></td>
    <td></td>
  </tr> {% endcomment %}
  <tr>
    <td>tear sheets</td>
    <td>{{tear_sheets |length}}</td>
    <td>{{tear_sheets__last_updated.updated_on}}</td>
  </tr>
  <tr>
    <td>tearsheet price records</td>
    <td>{{price_records | length}}</td>
    <td></td>
  </tr>
  {% comment %} <tr>
    <td class="text-center"><strong>FORMULA TEAR SHEETS</strong></td>
    <td></td>
    <td></td>
  </tr> {% endcomment %}
  <tr>
    <td>formula tear sheets</td>
    <td>{{formula_tear_sheets |length}}</td>
    <td>{{formula_tear_sheets__last_updated.updated_on}}</td>
  </tr>
  <tr>
    <td>formula tearsheet price records</td>
    <td>{{formula_tear_sheets__price_records | length}}</td>
    <td></td>
  </tr>
  {% comment %} <tr>
    <td class="text-center"><strong>PRICE LIST RECORDS</strong></td>
    <td></td>
    <td></td>
  </tr> {% endcomment %}
  <tr>
    <td>price list price records</td>
    <td>{{pricelist_records |length}}</td>
    <td>{{ pricelist_records__last_updated.updated_on }}</td>
  </tr>
  {% comment %} <tr>
    <td class="text-center"><strong>FORMULA PRICE LIST RECORDS</strong></td>
    <td></td>
    <td></td>
  </tr> {% endcomment %}
  <tr>
    <td>formula price list price records</td>
    <td>{{formula_price_list__price_records |length}}</td>
    <td>{{formula_price_list__last_updated.updated_on }}</td>
  </tr>
</table>

{% endblock content %}